ui_print "~ Verifying Device ...                           "

device_check "kenzo"|"kate"

ui_print "-------------------------------------------------"
ui_print "           GCam Patch for kenzo/kate         V1.3"
ui_print "              By @BoogeyWoogey69                 "
ui_print "  Major thanks to SerJo87 , Savitar, Kuro Shi,   "
ui_print "            Kiraryu and Ayush Rathore            "
ui_print "-------------------------------------------------"
ui_print " "
ui_print "~ List of patches -                              "
ui_print "1. 60 FPS video recording                   (1.2)"
ui_print "2. Green tint fix for front cam             (1.0)"
ui_print "3. Viewfinder lag fix                       (1.0)"
ui_print "4. 4k DCI Support                           (1.2)"
ui_print "5. Increased Maximum ISO value - 12,800     (1.2)"
ui_print "6. Constant framerates when shooting videos (1.2)"
ui_print "7. Improved Denoising for 30 fps videos     (1.2)"
