ui_print "~ Verifying Device ...                           "
device_check "kenzo"|"kate"

ui_print "-------------------------------------------------"
ui_print "           GCam Module for kenzo/kate            "
ui_print "              By @BoogeyWoogey69                 "
ui_print "            Current Version - V1.4               "
ui_print "-------------------------------------------------"
ui_print " "
ui_print "~ List of features -                             "
ui_print "1. 60 FPS video recording                        "
ui_print "2. Green tint fix for front cam                  "
ui_print "4. 4k DCI Support                                "
ui_print "5. Increased Maximum ISO value - 12,800          "
ui_print "6. Constant framerates when shooting videos      "
ui_print "7. Improved Denoising for 30 fps videos          "
ui_print "8. Codec2 Support                                "
ui_print "-------------------------------------------------"

ui_print "~ Enabling Codec2 ...                            "
prop_process $MODPATH/common/custom.prop
